enabled: false
language: python
dist: focal
matrix:
  fast_finish: true
  include:
    - python: '3.11'
    - python: '3.10'
    - python: '3.9'
      dist: xenial
    - python: '3.8'
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m unittest tests.test_gascomp
branches:
  only:
    - master