language: python
dist: focal
matrix:
  fast_finish: true
  include:
    - python: 'pypy3'
    - python: '3.12'
    - python: '3.10'
    - python: '3.10'
      dist: bionic
    - python: '3.9'
    - python: '3.8'
    - python: '3.7'
    - python: '3.6'
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m unittest tests.test_gascomp